meta_product_name: "BriefCases"
meta_title: "BriefCases - Make the case easy for your clients"
meta_description: "Create a customizable analysis to send to your clients and generate leads"
meta_image: "FB.png"                       # should exist in `app/assets/images/`
